### ISSUE TITLE
Add an explorer link

### ISSUE THREAD

**Issue by arkan** [deadcast/ChainTrack#2]
Hey,

It could be great to add a link to access an explorer such as this one http://104.238.153.140:3001 for each address. 

Basically a link could be added here 
![](https://f001.backblazeb2.com/file/screenshots-8698cd7c03d03b3d03178c87346e0618/Screen-Shot-2017-12-14-12-53-04.png) 

The link could be `http://104.238.153.140:3001/address/{{.COINCOIN_ADDRESS}}`, which would make the exploration easier :) 

What do you think?

**Comment by deadcast** [comment]
Excellent idea! Thanks for suggesting this. I just added the change and deployed it. :)
